# Generated by Django 5.1.4 on 2024-12-16 06:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_paymentdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInOutRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('check_in', 'Check In'), ('check_out', 'Check Out')], max_length=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CheckinOut', to='members.member')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
