# Generated by Django 5.1.4 on 2024-12-19 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_checkinoutrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.CharField(default='Male', max_length=6),
            preserve_default=False,
        ),
    ]
