# Generated by Django 5.1.4 on 2024-12-19 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_reminders'),
    ]

    operations = [
        migrations.CreateModel(
            name='gym_reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('attendance', 'Attendance Reminder'), ('expiry', 'Subscription Expiry Reminder'), ('inactive', 'Inactive Membership Reminder')], max_length=20)),
                ('is_sent', models.BooleanField(default=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='members.member')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.DeleteModel(
            name='reminders',
        ),
    ]
