# Generated by Django 5.1.4 on 2024-12-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_gym_reminder_delete_reminders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym_reminder',
            name='category',
            field=models.CharField(choices=[('attendance', 'Attendance Reminder'), ('expiry', 'Subscription Expiry Reminder')], max_length=20),
        ),
    ]
