# Generated by Django 5.1.4 on 2024-12-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_alter_gym_reminder_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_frozen',
            field=models.BooleanField(default=False),
        ),
    ]
