# Generated by Django 5.1.4 on 2024-12-24 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_memberprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
