# Generated by Django 5.1.4 on 2024-12-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_alter_member_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Positive balance indicates credit, negative indicates debt', max_digits=10),
        ),
    ]
