# Generated by Django 5.1.4 on 2024-12-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_member_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='plan',
            field=models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('biannually', 'Biannually'), ('annually', 'Annually'), ('student', 'Student Package'), ('complete', 'Complete Payment')], max_length=20, verbose_name='Payment Plan'),
        ),
    ]
