# Generated by Django 5.1.4 on 2025-01-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_gymreminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymreminder',
            name='reminder',
            field=models.TextField(default='Y'),
            preserve_default=False,
        ),
    ]
