# Generated by Django 5.1.4 on 2025-01-03 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0019_gymreminder_reminder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GymReminder',
        ),
    ]
