# Generated by Django 5.1.4 on 2025-01-03 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0020_delete_gymreminder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gym_reminder',
            options={'ordering': ['-created_at']},
        ),
    ]
