# Generated by Django 5.1.4 on 2025-01-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0022_expense_details_alter_expense_expense_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='membership_expiry',
            field=models.DateField(blank=True, help_text='Date when the membership expires', null=True),
        ),
    ]
