# Generated by Django 5.1.4 on 2025-01-06 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0023_member_membership_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freeze_member',
            name='freeze_time',
        ),
    ]
