# Generated by Django 5.1.4 on 2025-01-06 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0024_remove_freeze_member_freeze_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeze_member',
            name='freeze_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freeze_member',
            name='unfrozen_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freeze_member',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member'),
        ),
    ]
