# Generated by Django 5.1.4 on 2025-01-13 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0027_member_balance_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='members.member'),
            preserve_default=False,
        ),
    ]
