# Generated by Django 5.1.4 on 2025-01-13 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0028_task_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='member',
        ),
        migrations.AddField(
            model_name='task',
            name='member_id',
            field=models.ForeignKey(default=56, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='members.member'),
            preserve_default=False,
        ),
    ]
