# Generated by Django 5.1.4 on 2025-01-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0029_remove_task_member_task_member_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='member_id',
        ),
        migrations.AddField(
            model_name='task',
            name='member',
            field=models.IntegerField(default=56),
            preserve_default=False,
        ),
    ]
