# Generated by Django 5.1.4 on 2025-01-13 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0030_remove_task_member_id_task_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='member',
        ),
    ]
