# Generated by Django 5.1.4 on 2025-01-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0031_remove_task_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='member',
            field=models.IntegerField(default=1),
        ),
    ]
